### ISSUE TITLE
Request for kernel source code for Moto G Power 5G (devonn, T1TOS33.33-45-23-1)

### ISSUE THREAD

**Issue by dynamikmechanik** [MotorolaMobilityLLC/kernel-mtk#100]
Hi, I am a developer who is interested in working on the Moto G Power 5G. I would like to request the kernel source code for the device with the following specifications:

- Model: Moto G Power 5G
- Build Number: T1TOS33.33-45-23-1
- Codename: devonn

I would appreciate it if you could provide me with the kernel source code for this device. Thank you for your time.

**Comment by dynamikmechanik** [comment]
Please help @asbraga-motorola @chenyt9 @LONGCHEER-01 sorry to call you out

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T1TOS33.33-45-23-1
