### ISSUE TITLE
Kernel Source for <QOGS30.569-83-18>

### ISSUE THREAD

**Issue by kjhota123** [MotorolaMobilityLLC/kernel-mtk#105]
### Build ID

Device: Motorola Moto e7 (malta_64) — 4 gigabytes of RAM, 64 gigabytes of internal storage
Model: XT2095-1
Build: QOGS30.569-83-18 (seemingly the latest available to download)

### Additional

I am dipping my toes

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-QOGS30.569-83-18
