### ISSUE TITLE
[Request] Kernel source for moto edge 40 neo
T3TMS33.23-100-3-1

### ISSUE THREAD

**Issue by sr0077** [MotorolaMobilityLLC/kernel-mtk#106]
Please release the latest kernel source
Build No: **T3TMS33.23-100-3-1**

**Comment by chenyt9** [comment]
@sr0077 
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T3TMS33.23-100-3-1
