### ISSUE TITLE
Stock ROM for Moto edge 40 neo Build no - T3TM33.23-141-2

### ISSUE THREAD

**Issue by ijohnwickx** [MotorolaMobilityLLC/kernel-mtk#109]
### Build ID

Please release Stock ROM for Moto edge 40 neo with Build no T3TM33.23-141-2 updated on February 1,2024.

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T3TM33.23-141-2
