### ISSUE TITLE
Kernel Source for T2SVS33.68-21-8-2

### ISSUE THREAD

**Issue by Finite-Code** [MotorolaMobilityLLC/kernel-mtk#110]
### Build ID

T2SVS33.68-21-8-2

### Additional

Of course, I'll make custom ROMs, lol

just revising the info -- I need kernel source for moto g72 (vicky)

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T2SVS33.68-21-8-2
