### ISSUE TITLE
Device tree for Moto G54 5G?

### ISSUE THREAD

**Issue by the-arxyn** [MotorolaMobilityLLC/kernel-mtk#111]
### Build ID

MMI-T3TD33.16-22-5

### Additional

Device trees for G54 5G (MMI-T3TD33)

**Comment by Finite-Code** [comment]
You're directly requesting a device tree? bold attempt, if they give it then it's 🔥

**Comment by chenyt9** [comment]
@the-arxyn  @Finite-Code 
Please refer to this URL:
https://github.com/MotorolaMobilityLLC/kernel-mtk/tree/MMI-T3TD33.16-22-5/arch/arm64/boot/dts/mediatek
