### ISSUE TITLE
Kernel Source for S3RHS32.20-42-10-4-11

### ISSUE THREAD

**Issue by YasogaN** [MotorolaMobilityLLC/kernel-mtk#112]
### Build ID

S3RHS32.20-42-10-4-11

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3RHS32.20-42-10-4-11

**Comment by YasogaN** [comment]
@asbraga-motorola Thank you so much.
