### ISSUE TITLE
[Request] Kernel source code for motorola G54 5G (U1TD34.94-12-7)

### ISSUE THREAD

**Issue by Sureshgorai25** [MotorolaMobilityLLC/kernel-mtk#113]
### Build ID

U1TD34.94-12-7

### Additional

Please release kernel sources for moto g54 5g android 14.
Build Number: U1TD34.94-12-7

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-U1TD34.94-12-7

**Comment by sarthakroy2002** [comment]
@asbraga-motorola Wlan and bt kernel modules U1TD34.94-12-7 aren't pushed 
Please push it

**Comment by Sureshgorai25** [comment]
> Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-U1TD34.94-12-7

Can you please push wlan/core/gen4m drivers of the same build

**Comment by asbraga-motorola** [comment]
code for wlan/core/gen4m: https://github.com/MotorolaMobilityLLC/vendor-mediatek-kernel_modules-connectivity-wlan-core-gen4m/releases/tag/MMI-U1TD34.94-12-7

**Comment by sarthakroy2002** [comment]
Thanks

**Comment by forforksake** [comment]
Can you update for U1TD34.94-12-9-10 please?

**Comment by asbraga-motorola** [comment]
> Can you update for U1TD34.94-12-9-10 please?

Could you please open a new issue for that Build ID?
