### ISSUE TITLE
Kernel Source for <MMI-S3RWBS32.125-29-2-4-3>

### ISSUE THREAD

**Issue by Swastik369** [MotorolaMobilityLLC/kernel-mtk#115]
### Build ID

S3RWBS32.125-29-2-4-3

### Additional

> defconfig , where can we find it
Branch name is (MMI-S3RWBS32.125-29-2-4-3)

**Comment by Finite-Code** [comment]
Hello buddy

**Comment by sergiosvmot** [comment]
you can find it at 

arch/arm64/configs
