### ISSUE TITLE
Kernel source code for motorola G54 5G (T3TDS33.16-78-2-2)

### ISSUE THREAD

**Issue by wozouyu** [MotorolaMobilityLLC/kernel-mtk#117]
### Build ID

Build ID
T3TDS33.16-78-2-2

Additional
Please release kernel sources for moto g54 5g android 13.
Build Number: T3TDS33.16-78-2-2

**Comment by chenyt9** [comment]
@wozouyu，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T3TDS33.16-78-2-2
