### ISSUE TITLE
Kernel Source for moto g23 

### ISSUE THREAD

**Issue by u8void** [MotorolaMobilityLLC/kernel-mtk#118]
### Build ID

THAS33.31-40-3

### Additional

I really need kernel source for moto g23 to make custom roms

**Comment by electimon** [comment]
@mbissaromoto @chenyt9 please

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-THAS33.31-40-3
