### ISSUE TITLE
Kernel Source for U1TNS34.82-12-7-2 (Moto G73 5g  (devonf) - retbr)

### ISSUE THREAD

**Issue by S1xApelon** [MotorolaMobilityLLC/kernel-mtk#120]
### Build ID

U1TNS34.82-12-7-2

### Additional

Por favor libere as fontes do Kernel do Moto G73 5g - XT2237-1

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-U1TNS34.82-12-7-2
