### ISSUE TITLE
Kernel Source for U1TM34.107-34-3 (Motorola Edge 40 Neo){manaus}

### ISSUE THREAD

**Issue by justsarx** [MotorolaMobilityLLC/kernel-mtk#121]
### Build ID

U1TM34.107-34-3

### Additional

Kindly provide kernel source for motorola/manaus_g_sys/manaus:14/U1TM34.107-34-3/1c7ca3-65ae8:user/release-keys

**Comment by justsarx** [comment]
Any update @chenyt9 ?

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-U1TM34.107-34-3
