### ISSUE TITLE
Kernel tree for S3RLS32.114-25-13 (Lisbon)

### ISSUE THREAD

**Issue by felipeskyy** [MotorolaMobilityLLC/kernel-mtk#125]
### Build ID

S3RLS32.114-25-13

### Additional

I need the complete kernel tree with all mediatek proprietary drivers, if they are not implemented.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3RLS32.114-25-13
