### ISSUE TITLE
Kernel Source for Moto G8 Power Lite (blackjack_64)

### ISSUE THREAD

**Issue by katakishi0** [MotorolaMobilityLLC/kernel-mtk#127]
### Build ID

QOD30.160-26 44153

### Additional

Please release moto G8 Power Lite sources for QOD30.160-26 44153 build

**Comment by asbraga-motorola** [comment]
This is Blackjack Q, end of life more than 3 years ago, we don’t have any of source code / compiling environment / SW build. So it’s unavailable to support this open source.
Sorry for that.
