### ISSUE TITLE
Kernel Source for U4UI34.8-22-7

### ISSUE THREAD

**Issue by TadiT7** [MotorolaMobilityLLC/kernel-mtk#132]
### Build ID

U4UI34.8-22-7

### Additional

The device is Edge 50 Neo, XT2409-1, please include kernel modules.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-U4UI34.8-22-7
