### ISSUE TITLE
[GPL - Kernel Source Request] for motorola edge 40 neo (manaus) - U1TMS34.107-34-4-2

### ISSUE THREAD

**Issue by rexix01** [MotorolaMobilityLLC/kernel-mtk#135]
### Build ID

**Build ID**
U1TMS34.107-34-4-2

**Additional**
Hello there!
Could you kindly provide the kernel sources along with the usual vendor/modules/device tree and all the necessary packages for the Motorola Edge 40 Neo (manaus) version 
### U1TMS34.107-34-4-2

While processing this request, please take care to include all of the things mentioned.

Codename: Manaus
Release: U1TMS34.107-34-4-2
Model Number (SKU): XT2307-1

Greetings, moto-team!
I really appreciate what you do

Notif: @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-U1TMS34.107-34-4-2
