### ISSUE TITLE
Kernel source for Moto g23 Android 14 - UHAS34.29-3

### ISSUE THREAD

**Issue by u8void** [MotorolaMobilityLLC/kernel-mtk#136]
### Build ID

UHAS34.29-3

### Additional

Providing kernel source can help us to take better experience

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-UHAS34.29-3

**Comment by u8void** [comment]
> Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-UHAS34.29-3

Why you blocked us from unlock bootloader it's not fair moto g41 is lower price and unlockable please make moto g23 can be unlocked bootloader

**Comment by R0rt1z2** [comment]
@asbraga-motorola would it be possible to also include penangf's `cust.dtsi` (`#include <penangf/cust.dtsi>`)?

**Comment by asbraga-motorola** [comment]
> [@asbraga-motorola](https://github.com/asbraga-motorola) would it be possible to also include penangf's `cust.dtsi` (`#include <penangf/cust.dtsi>`)?

That file is a compiled product and is not included in the code, so we cannot provide it

**Comment by R0rt1z2** [comment]
> > [@asbraga-motorola](https://github.com/asbraga-motorola) would it be possible to also include penangf's `cust.dtsi` (`#include <penangf/cust.dtsi>`)?
> 
> That file is a compiled product and is not included in the code, so we cannot provide it

@asbraga-motorola how about codegen.dws?

**Comment by progzone122** [comment]
> > > [@asbraga-motorola](https://github.com/asbraga-motorola) would it be possible to also include penangf's `cust.dtsi` (`#include <penangf/cust.dtsi>`)?
> > 
> > 
> > That file is a compiled product and is not included in the code, so we cannot provide it
> 
> [@asbraga-motorola](https://github.com/asbraga-motorola) how about codegen.dws?

@asbraga-motorola
