### ISSUE TITLE
Complete Kernel Source for MMI-T2RK33.146-14-1 (kyoto)

### ISSUE THREAD

**Issue by nift4** [MotorolaMobilityLLC/kernel-mtk#137]
### Build ID

MMI-T2RK33.146-14-1

### Additional

https://github.com/MotorolaMobilityLLC/vendor-mediatek-kernel_modules-connectivity-bt-mt66xx
This repository was missed during the push of MMI-T2RK33.146-14-1

**Comment by liuya9** [comment]
This repository has been added in MMI-T2RK33.146-14-1.

**Comment by nift4** [comment]
thanks
