### ISSUE TITLE
Kernel source Moto G54 android 14 - U1TD34.94-12-9-10

### ISSUE THREAD

**Issue by forforksake** [MotorolaMobilityLLC/kernel-mtk#140]
### Build ID

U1TD34.94-12-9-10

### Additional

Please release kernel sources for moto g54 5g android 14.
 Build Number: U1TD34.94-12-9-10

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-U1TD34.94-12-9-10
