### ISSUE TITLE
moto c plus (XT1721) kernel source

### ISSUE THREAD

**Issue by dhirajms** [MotorolaMobilityLLC/kernel-mtk#15]
**Please put source code for moto c plus **

![image](https://user-images.githubusercontent.com/27199664/34292208-ea962c16-e725-11e7-8e54-57011694ed26.png)

**Comment by dhirajms** [comment]
waiting for kernel source from last 3 months.....

**Comment by zhangheting407051** [comment]
@DhirajSurvase 
https://github.com/MotorolaMobilityLLC/kernel-mtk/tree/nougat-7.1.1-release-panelli
This is moto c plus kernel source code.
Best wishes!

**Comment by dhirajms** [comment]
thanks.....
