### ISSUE TITLE
Defconfig for Taido_row

### ISSUE THREAD

**Issue by HostZero** [MotorolaMobilityLLC/kernel-mtk#2]
I have this kernel source: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-XT1662-S0529-160920

i have gone trough commit history their is taido_row_debub_defconfig

but in kernel source i couldnt find kernel config.

which config i should use?

- HostZero

**Comment by jenish97** [comment]
Found defconfig
https://github.com/MotorolaMobilityLLC/kernel-mtk/tree/MMI-XT1706-S131-160905/arch/arm/configs

**Comment by HostZero** [comment]
Okay! So they are two different defconfigs.. Like
Mine is for XT1662. Is their any different defconfig. As the tag you have provided is of XT1706.

**Comment by jenish97** [comment]
Hey on link for taido defconfig file available for xt1706

**Comment by HostZero** [comment]
Thankyou! I will try a compile with that config.

**Comment by jenish97** [comment]
Any other which file miss
And can give your contact no. For what's app

And turjya shah port miui 8 camera and nav bar not work
My patch to volte work but volte symbol not show
