### ISSUE TITLE
Oreo kernel source of manning 

### ISSUE THREAD

**Issue by SamarV-121** [MotorolaMobilityLLC/kernel-mtk#23]
When you are gonna release Oreo kernel source of Lenovo K8 Note (manning) ?

**Comment by SamarV-121** [comment]
@chenyt9

**Comment by nikitsharma15** [comment]
+1

**Comment by revant** [comment]
+1

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-OMB27.43-45
Thanks.
