### ISSUE TITLE
for Moto E

### ISSUE THREAD

**Issue by Zormax** [MotorolaMobilityLLC/kernel-mtk#24]
@chenyt9 please put source 148 release for Moto E

**Comment by chenyt9** [comment]
@Zormax , NMA26.42-148?

**Comment by Zormax** [comment]
@chenyt9, yes

**Comment by Zormax** [comment]
@chenyt9, any news?

**Comment by chenyt9** [comment]
@Zormax ，
Because we have some necessary processes, so we need a little time. We will release NMA26.42-148 ASAP.
Thanks for understanding
BRs.
chenyt9

**Comment by chenyt9** [comment]
hi,@Zormax ，
Version released.
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-NMA26.42-148
Thanks.
