### ISSUE TITLE
Source code: Moto C Plus Update: NRD90M.03.041

### ISSUE THREAD

**Issue by dhirajms** [MotorolaMobilityLLC/kernel-mtk#25]
put updated source code of NRD90M.03.041 of moto c plus

**Comment by dhirajms** [comment]
@zhangheting407051

**Comment by LinuxPanda** [comment]
Please release latest source. Thanks.

**Comment by zhangheting407051** [comment]
@DhirajSurvase @LinuxPanda 
The source code of NRD90M.03.041 is the same as before.
thank you

**Comment by dhirajms** [comment]
BBBBye Moto.....................

**Comment by SamarV-121** [comment]
😂

**Comment by dhirajms** [comment]
Posted on OLX...
Chill life...
