### ISSUE TITLE
Moto E4

### ISSUE THREAD

**Issue by Zormax** [MotorolaMobilityLLC/kernel-mtk#27]
please put source NMA26.42-152 for E4

**Comment by Zormax** [comment]
@chenyt9

**Comment by chenyt9** [comment]
@Zormax ,
NMA26.42-152 for E4? Please confirm, is it Moto E or Moto E plus? I did not find the E4 version is NMA26.42-152?
Thanks.
BRs.
Yuting

**Comment by Zormax** [comment]
@chenyt9
            
for xt1762
a week ago, the OTA for the region reteu was updated to 152

https://ibb.co/nc1Omd

**Comment by chenyt9** [comment]
@Zormax ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-NMA26.42-152
Thanks.
BRs.
