### ISSUE TITLE
am I right : "Moto is ignoring Low Budget devices"??

### ISSUE THREAD

**Issue by dhirajms** [MotorolaMobilityLLC/kernel-mtk#28]
No Update for any old devices.....
moto c series is totally ignored by moto...
even stock are buggy af .....

**Comment by Zormax** [comment]
Here is another example:
Moto E4 - 113-148-152 latest firmware
Moto E4plus - only 113 firmware with OTA

**Comment by chenyt9** [comment]
@all，
If you have a version requirement, please post the project name and version number. Thanks.
@zhangheting407051

**Comment by chenyt9** [comment]
@Zormax ,
The lastest release is  updated : 
Moto E4 : https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-NMA26.42-146
Moto E4plus: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-NMA26.42-152

I don't quite understand what you mean, could you explain  it in more detail? Do you still have new version requirements?？
Thanks.

**Comment by chenyt9** [comment]
@zhangheting407051

**Comment by Zormax** [comment]
@chenyt9 no problem

**Comment by dhirajms** [comment]
Rip Moto...
