### ISSUE TITLE
Download verdor-lenovo-sdcardfs repo.

### ISSUE THREAD

**Issue by wizardik** [MotorolaMobilityLLC/kernel-mtk#3]
Maybe I was looking bad. But I did not find this directory in your repository. Please help.
MMI-XT1663-S0124-161215 for MOTO M

Download vendor-lenovo-exfat repo.  ++++
Download verdor-lenovo-sdcardfs repo.  -----

**Comment by mmehdi** [comment]
https://github.com/MotorolaMobilityLLC/vendor-lenovo-exfat
https://github.com/MotorolaMobilityLLC/vendor-lenovo-sdcardfs
