### ISSUE TITLE
port to kernel 3.4.5

### ISSUE THREAD

**Issue by sandibabsel** [MotorolaMobilityLLC/kernel-mtk#30]
Could i port this kernel to mtk devices that have kernel 3.4.5 chipset mt6572 android jb?

**Comment by LinuxPanda** [comment]
Not sure about that since "most" of these kernels are for device mt67xx & later.

Maybe try to find a device that uses mt6572 and try to port it. Check this, https://github.com/MediatekAndroidDevelopers.

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested on request, please re-open the issue.
