### ISSUE TITLE
NMA26.42-162|7-1 (GPS week rollover)

### ISSUE THREAD

**Issue by Zormax** [MotorolaMobilityLLC/kernel-mtk#33]
please put source for Moto E4 plus (NMA26.42-162-1) and Moto E4 (NMA26.42-167-1)

**Comment by Zormax** [comment]
@fusy1

**Comment by chenyt9** [comment]
@Zormax ,
Sorry ，We missed this issue.This is an early project, In 2018, we released two versions. I don’t know if they are all the versions you need.
Version url:
Moto E4 plus:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-NMA26.42-162
Moto E4: 
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-NMA26.42-167
Thanks.
