### ISSUE TITLE
Source request for build PTB29.401-25

### ISSUE THREAD

**Issue by philectro** [MotorolaMobilityLLC/kernel-mtk#34]
Hi, i request the availability of kernel source for MOTO E6 plus, PTB29.401-25, Model : xt2025-2

Thanks.

**Comment by TinnoOSS** [comment]
Hi @philectro,
We are working to release this version. It will be released by next week.
Thanks.

**Comment by TinnoOSS** [comment]
Hi @philectro,
PTA29.401-25 / PTB29.401-25 has been released, please check it.
Thanks.
