### ISSUE TITLE
Moto-E4-Plus Mediatek Nicklaus Need Help!!!!!!

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-mtk#35]
Hi there,
Can anyone tell me the following about my **Moto E4 Plus Mediatek Version XT1770 Codename Nicklaus kernel 3.18.35+ Nougat7.1.1**

1. Is it arm or arm64?
2. Is it MT6735 or MT6737 or MT6737M?
3. Is there any source code for my device?
4. What toolchain should I use arm or arm64?
5. Any documentation regarding the procedure of building custom kernel from source code if any?

Regards.

**Comment by chenyt9** [comment]
@BeingDatta ,
I think what you need is this file, this file is build instructions for nicklaus:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-NMA26.42-82.txt
1. arm
2. MT6737
3. This is a version of nicklaus: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-NMA26.42-82
Thanks.
