### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Anirudh-singh-Core** [MotorolaMobilityLLC/kernel-mtk#37]
I ran into some problem with oreo 8.0.0 (manning) Kali kernel , I request u to provide me the stock kernel back for it .

**Comment by chenyt9** [comment]
Hi，@Anirudh-singh-Core 
It's a version  of oreo 8.0.0 (manning)  
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-OMB27.43-45
Does this meet your needs?

**Comment by vinimed** [comment]
Hello @Anirudh-singh-Core, due to the long time without answer, we are closing the issue. If you are still interested in a version different from the one commented by Yuting, please re-open the issue.
