### ISSUE TITLE
[Request] Moto G8 Power Lite (blackjack) - QOD30.163-3 Kernel Sources

### ISSUE THREAD

**Issue by Deivid21** [MotorolaMobilityLLC/kernel-mtk#38]
Hey,
Could you release kernel sources for this version?
Thanks :)

**Comment by kytoaq** [comment]
Please release this version, developers need to work with the device. Thank's

**Comment by kytoaq** [comment]
@chenyt9 @charleseb Bump please :)

**Comment by ontimoss** [comment]
The workflow has been triggered and is expected to be completed within 3 weeks. Please be patient, thank you.

**Comment by kytoaq** [comment]
Release when ? 🤔 @ontimoss

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-QOD30.163-3
