### ISSUE TITLE
[Request] Motorola One Macro (lima) - QMD30.47-19 Kernel Sources 

### ISSUE THREAD

**Issue by menorziin** [MotorolaMobilityLLC/kernel-mtk#41]
Hey,
Could you release kernel sources for this version?
Thanks :)

**Comment by menorziin** [comment]
@chenyt9 @charleseb Bump please

**Comment by chenyt9** [comment]
Hi ,@menorziin ，
Sorry for the delay.
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-QMD30.47-19
Thanks.
