### ISSUE TITLE
[Request] Motorola One Macro (lima) - QMD30.47-19-2 Kernel Sources

### ISSUE THREAD

**Issue by kauan-wg** [MotorolaMobilityLLC/kernel-mtk#43]
Hey,
Could you release kernel sources for this version?
Thanks :)

**Comment by chenyt9** [comment]
Hi，@kauan-wg ，
Please help confirm the version，QMD30.47-19？or QMDS30.47-19-2？I cannot find version QMD30.47-19-2.

**Comment by kauan-wg** [comment]
> Hi，@kauan-wg ，
> Please help confirm the version，QMD30.47-19？or QMDS30.47-19-2？I cannot find version QMD30.47-19-2.
> 

hi, sorry for the mistake the correct version is QMDS30.47-19-4
