### ISSUE TITLE
[REQUEST]: Moto G8 Play (lima_32) - QDM30.47-34 Kernel Source

### ISSUE THREAD

**Issue by kytoaq** [MotorolaMobilityLLC/kernel-mtk#45]
Hi Moto !

Please, can push this TAG and all relevant sources for this device? Thanks you ! :)

**Comment by chenyt9** [comment]
Hi @kytoaq  ,
I think what you need is QMD30.47-34 version. We are working to release this version. It will be released by next week.
Thanks.

**Comment by kytoaq** [comment]
Awesome. Thanks you

**Comment by chenyt9** [comment]
Hi, @kytoaq ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-QMD30.47-34
Thanks for your patient.
