### ISSUE TITLE
[Request] Motorola One Macro (lima) - QMDS30.47-33-2 Kernel Sources

### ISSUE THREAD

**Issue by BearusuMyo** [MotorolaMobilityLLC/kernel-mtk#47]
Greetings,

Could you please release the Kernel sources for this version?

Thank you and have a nice day.

**Comment by chenyt9** [comment]
Hi @BearusuMyo ,
We are working to release this version. It will be released by next week.
Thanks.

**Comment by BearusuMyo** [comment]
Thank you very much!

**Comment by chenyt9** [comment]
@BearusuMyo ， release QMDS30.47-33-1 first. If you need QMDS30.47-33-2, we need to re-triger another release process.
Version is here：https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-QMDS30.47-33-1

**Comment by BearusuMyo** [comment]
Oh sure, take your time. Although I will be closing this issue since it's original request was accomplished. Thank you very much once more.
