### ISSUE TITLE
Building issues on pie-9.0.0-poker branch

### ISSUE THREAD

**Issue by KatoTempest** [MotorolaMobilityLLC/kernel-mtk#48]
I have tried to compile the kernel for the motorola e6 plus, the arm64 variant, I found in github the instructions on how to do it, perp after doing the whole procedure at the end I receive an error, which says something similar to this "makefile: error no. 2"

**Comment by asbraga-motorola** [comment]
I'm closing this issue as it is too old and did not inform the specific build id. Please open a new one if still necessary.
