### ISSUE TITLE
GPL | Source request for Motorola Moto Edge 20 Lite (Kyoto) RRK31.Q3-19-97

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-mtk#49]
CC: @chenyt9

**Comment by chenyt9** [comment]
Hi，@Hasaber8 ，
I have triggered the release process of the version, it may take at least two weeks, thank you in advance for your patience.

**Comment by Hasaber8** [comment]
Thank you @chenyt9

**Comment by Hasaber8** [comment]
@chenyt9 @awheeler-mmi it's been over a month now.

**Comment by forforksake** [comment]
@chenyt9 can you please share your progress on this
Many thanks

**Comment by ghost** [comment]
Well I wanted to ask is fusion variant also known as Kyoto ?

**Comment by Hasaber8** [comment]
> Well I wanted to ask is fusion variant also known as Kyoto ?

Yep its the same.

**Comment by forforksake** [comment]
Just dimensity 800 for fusion and 720 for lite

**Comment by ghost** [comment]
So do we have sources yet, i.e
Kernel Trees
Device Trees
Vendor Trees

**Comment by Hasaber8** [comment]
Fyi vendor and device trees are proprietary.
Only kernel tree is released.

**Comment by ghost** [comment]
So we can start developing initial oss device Trees, right ?

**Comment by ghost** [comment]
Is someone working on this

**Comment by ghost** [comment]
@Hasaber8 sir plz answer if you can

**Comment by forforksake** [comment]
I've started looking at it.
Just gathering what I can from the boot.img
Will take another look later hopefully

**Comment by chenyt9** [comment]
Hi，all，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRK31.Q3-19-97
Thank you all for your patience！
