### ISSUE TITLE
Many Files are missing !!

### ISSUE THREAD

**Issue by SamarV-121** [MotorolaMobilityLLC/kernel-mtk#5]
WTF 
Many Files are missing !! in kernel source of Moto E3 Power 
MMI-XT1706-S131-160905
I wanna compile kernel -_ 
@motorolamobilityllc @zhangxu21
Waiting for reply .

**Comment by chenyt9** [comment]
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-XT1706-S131-160905.txt

Please download the code with the tag and compile it according to the above file：MMI-XT1706-S131-160905.txt.

thanks.

**Comment by SamarV-121** [comment]
OK will try

**Comment by dragonpt** [comment]
Your just too damn stupid!

What files are missing?

Doesn't compile ? Lol

Why do you even want to build a kernel if you are just clueless how to do so?
