### ISSUE TITLE
[Request] Moto g31 kernel (cofud)

### ISSUE THREAD

**Issue by squidink7** [MotorolaMobilityLLC/kernel-mtk#50]
Hi!
Could you please release the sources for this kernel?
Thank you!

**Comment by vinimed** [comment]
Hello @squidink7,

Can you please specify the release number you want? By having the release number we can focus on releasing the exact version you need.

Vinicius

**Comment by squidink7** [comment]
Just the latest you have available would be fine, thank you!

**Comment by chenyt9** [comment]
Hi，@squidink7 ，will arrange the release for cofud. Thanks

**Comment by chenyt9** [comment]
Hi,@squidink7  
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRWD31.Q3-26-83
