### ISSUE TITLE
[Request] Moto G22 Kernel Sources - STA32.79-13-2

### ISSUE THREAD

**Issue by techyminati** [MotorolaMobilityLLC/kernel-mtk#52]
Hello @motorolamobility please push Moto G22 Kernel Sources

**Comment by techyminati** [comment]
@chenyt9

**Comment by vinimed** [comment]
Hello @techyminati, could you please specify the version you want?

**Comment by techyminati** [comment]
Hi @vinimed Android Version - 12. Codename - hawaiip

**Comment by techyminati** [comment]
Also @vinimed Moto Tab G20 Android 11 Kernel Sources Please

**Comment by asbraga-motorola** [comment]
Hi @techyminati,
We need to known the exact released version you want. Example: RRS31.QX-YY-ZZ

**Comment by techyminati** [comment]
> Hi @techyminati, We need to known the exact released version you want. Example: RRS31.QX-YY-ZZ

How can I find a release version? Is it in about phone settings?

**Comment by asbraga-motorola** [comment]
You find it in the System Config in the phone. It is a group of letters and numbers, that look similar to these ones: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2, ...

**Comment by techyminati** [comment]
hi @asbraga-motorola STA32.79-13-2 this version

**Comment by techyminati** [comment]
@asbraga-motorola @chenyt9 any update?

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-STA32.79-13-2

**Comment by techyminati** [comment]
Thanks

**Comment by techyminati** [comment]
@asbraga-motorola commit history is not available
