### ISSUE TITLE
[Request] moto g pure ellis xt2163-4 kernel source

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-mtk#53]
hello, is there kernel source for the android 11 RRH31.Q3.46-113, mtk moto g pure xt2163-4?

**Comment by chenyt9** [comment]
Hi,@threadburner64 , will arrange the release for RRH31.Q3.46-113. Thank you for your patient.

**Comment by chenyt9** [comment]
@threadburner64 
Version released:

https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRH31.Q3-46-123

https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRH31.Q3-46-113

Thanks.
