### ISSUE TITLE
Moto G20 kernel source (java) XT2128-1 Tag RTAS31.68-34-2

### ISSUE THREAD

**Issue by SantiiAgoo5121** [MotorolaMobilityLLC/kernel-mtk#55]
Please could you post the kernel source code? We need to work with this device

**Comment by vinimed** [comment]
Hello @SantiiAgoo5121,

Could you please specify the version you want?

Thank you.

**Comment by SantiiAgoo5121** [comment]
@vinimed Hi! this version RTA31.42-5-5

**Comment by SantiiAgoo5121** [comment]
Or RTA31.68-29 
Is new

**Comment by SantiiAgoo5121** [comment]
@vinimed @chenyt9

**Comment by TinnoOSS** [comment]
@ALL,version released:
https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-RTAS31.68-34-2
