### ISSUE TITLE
[Request] Moto G50 5G Kernel Sources

### ISSUE THREAD

**Issue by alienatiz** [MotorolaMobilityLLC/kernel-mtk#57]
I want to improve Moto G50 5G (codenamed as "saipan"). 
Can I receive the kernel source data of Moto G50 5G?

(branch needed as "android-11-release-rrs")

**Comment by vinimed** [comment]
Hello @alienatiz,

Could you please specify the version you are looking for? 
Thank you.

**Comment by alienatiz** [comment]
> 

Android version 11, and its codename is saipan.

**Comment by alienatiz** [comment]
> Hello @alienatiz,
> 
> Could you please specify the version you are looking for? Thank you.

Android version 11, and its codename is saipan.

**Comment by mbissaromoto** [comment]
Hi @alienatiz 

We need to known the exact released version you want. Example: RRS31.QX-YY-ZZ

**Comment by alienatiz** [comment]
> Hi @alienatiz
> 
> We need to known the exact released version you want. Example: RRS31.QX-YY-ZZ

Here it is, RRSS31.Q2-54-59-6

**Comment by chenyt9** [comment]
Hi, @alienatiz , will arrange the release for RRSS31.Q2-54-59-6.

**Comment by SantiiAgoo5121** [comment]
> Hi, @chenyt9  . Can you help me? I need Moto G20 Kernel Sources RTA31.68-29

**Comment by chenyt9** [comment]
Hi, @alienatiz ,
Version released:https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/RRSS31.Q2-54-59-6
Thanks.

**Comment by alienatiz** [comment]
> Hi, @alienatiz , Version released:https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/RRSS31.Q2-54-59-6 Thanks.

Thanks, I've checked it.
