### ISSUE TITLE
Moto E40 Kernel sources ROQ31.166-37

### ISSUE THREAD

**Issue by kross055** [MotorolaMobilityLLC/kernel-mtk#58]
Please provide the kernel source for moto e40 version ROQ31.166-37

**Comment by FuccDucc** [comment]
@chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

Motorola is violating the GPL laws

**Comment by asbraga-motorola** [comment]
Code is published in repo kernel-sprd: https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-ROQ31.166-37
