### ISSUE TITLE
Moto-M_XT1663_S356_170621_ROW

### ISSUE THREAD

**Issue by 3apa3a** [MotorolaMobilityLLC/kernel-mtk#6]
Is there any source code for the Moto-M_XT1663_S356_170621_ROW kernel Android 7?

**Comment by pureexe** [comment]
Looking for Moto-M_XT1663 too.
My running device build is Moto-M_XT1663_S364_170803_ROW
but any build of source code is fine.

**Comment by chenyt9** [comment]
@3apa3a @pureexe ，
Version is released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/tree/MMI-XT1663-S356-170621
Thanks.

**Comment by pureexe** [comment]
@chenyt9 thank you for your release.
