### ISSUE TITLE
[Request] Moto e6s (Fiji) Kernel sources

### ISSUE THREAD

**Issue by refrigerador67** [MotorolaMobilityLLC/kernel-mtk#63]
Hello.
Can you release the kernel source for moto e6s (Fiji)?
Latest version is ok
Thanks in advance

**Comment by vinimed** [comment]
Hello @refrigerador67 ,

Could you please specify the exactly version you want?

Thank you.

**Comment by refrigerador67** [comment]
Hi @vinimed 
Can be POBS29.288-60-6-1-29?

**Comment by refrigerador67** [comment]
Hi again @vinimed, @chenyt9 
Could be also POES29.288-60-6-1-29?

**Comment by refrigerador67** [comment]
Bumping @vinimed @chenyt9

**Comment by darltrash** [comment]
any updates? @vinimed

**Comment by ItsIgnacioPortal** [comment]
> Hello. Can you release the kernel source for moto e6s (Fiji)? Latest version is ok Thanks in advance

Is this not the kernel source for the moto e6s? https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-POBS29.288-60-6-1-29
