### ISSUE TITLE
[REQUEST] Motorola Moto Tab G70 (mototabg70) - g70_LTE_S200145_230629_ROW Kernel Source

### ISSUE THREAD

**Issue by Mashopy** [MotorolaMobilityLLC/kernel-mtk#64]
Hi, could you release the kernel source for this version ? Thanks

**Comment by Mashopy** [comment]
@chenyt9 Any update ?

**Comment by chenyt9** [comment]
@Mashopy Can you inform the exact released version you want? You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

**Comment by Mashopy** [comment]
Motorola tablets doesn't have that kind of version naming but I request for g70_LTE_S200145_230629_ROW version
