### ISSUE TITLE
[Request] Moto G22 (hawaiip) - STA32.79-77-28

### ISSUE THREAD

**Issue by mikoxyz** [MotorolaMobilityLLC/kernel-mtk#65]
Hi,

Please push the kernel source code for build STA32.79-77-28.

**Comment by julienrobin28** [comment]
Hi, I'm looking for it me too!

**Comment by mikoxyz** [comment]
Bumping and paging @chenyt9

**Comment by mikoxyz** [comment]
Bumping and paging @chenyt9 again.

**Comment by mikoxyz** [comment]
Paging @chenyt9, @vinimed, and @mbissaromoto.

**Comment by TinnoOSS** [comment]
@all,version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-STA32.79-77-28
