### ISSUE TITLE
(Request) Motorola One Macro (lima) - QMDS30.47-33-5 Kernel Sources

### ISSUE THREAD

**Issue by RadioactivePlays** [MotorolaMobilityLLC/kernel-mtk#66]

**Comment by chenyt9** [comment]
@RadioactivePlays ，
The release process for this version has been triggered. Please be patient. Thanks!

**Comment by RadioactivePlays** [comment]
Waiting for it. Thank you sm

**Comment by chenyt9** [comment]
@RadioactivePlays ，Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-QMDS30.47-33-5
