### ISSUE TITLE
Request to release Kernel sources 

### ISSUE THREAD

**Issue by MelonMusk93** [MotorolaMobilityLLC/kernel-mtk#67]
Request you to release Kernel sources for Moto E40 2021 Cyprus ROQS31.166-42-1

Device Details - `https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.motorola.in/smartphones-moto-e40/p&ved=2ahUKEwjwmMjXkJP5AhX1-TgGHbjLAK0QFnoECAkQAQ&usg=AOvVaw3RqafG3uPQpiCZZ1ECv5et`

**Comment by FuccDucc** [comment]
@chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

Motorola is violating the GPL laws

**Comment by asbraga-motorola** [comment]
The code is published in repo kernel-sprd: https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-ROQS31.166-42-1
