### ISSUE TITLE
Request for kernel source XT2213-3(Austin) S1SAS32.47-59-7

### ISSUE THREAD

**Issue by damnthefall** [MotorolaMobilityLLC/kernel-mtk#68]
Please release the kernel sources for the Moto G 5G (2022)

**Comment by chenyt9** [comment]
Hi, @damnthefall ,
Austin released: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S1SA32.47-77
Please use this version first, we will prepare for the release of version S1SAS32.47-59-7.
Thank you for your patience.

**Comment by chenyt9** [comment]
Hi, @damnthefall ,
Austin released: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S1SA32.47-77
Please use this version first, we will prepare for the release of version S1SAS32.47-59-7.
Thank you for your patience.

**Comment by damnthefall** [comment]
Thank you!

**Comment by chenyt9** [comment]
@damnthefall 
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S1SAS32.47-59-7
