### ISSUE TITLE
Request Kernel Sources TONGA RRQS31.Q3.68.149-2

### ISSUE THREAD

**Issue by Ekylypse** [MotorolaMobilityLLC/kernel-mtk#69]
Request Kernel Sources TONGA RRQS31.Q3.68.149-2 using MediaTek Helio G37 (MT6765H)

**Comment by chenyt9** [comment]
@Ekylypse ,
This version RRQS31.Q3.68.149-2 is already on our release list, thank you very much for your patience. We will publish it as soon as possible.
Here is two release for Moto g power ：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRQS31.Q3-68-140-2
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRQ31.Q3-68-16-2R1
Can you please use those version first？Thanks a lot.

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRQS31.Q3-68-149-2
