### ISSUE TITLE
GPL | Source request for Motorola Moto Edge 20 Lite (Kyoto) S2RKS32.92-11-21-3

### ISSUE THREAD

**Issue by nift4** [MotorolaMobilityLLC/kernel-mtk#70]
CC: @chenyt9

**Comment by asbraga-motorola** [comment]
Hi @nift4,
The code you requested is in the pipeline for publication.
This other version is already published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S2RK32.92-11-21.

**Comment by nift4** [comment]
Thank you for the update!

**Comment by asbraga-motorola** [comment]
The code is published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S2RKS32.92-11-21-3
