### ISSUE TITLE
Kernel Sources for Moto G72 (Victoria) MTK G99 S3SV32.45-24-3

### ISSUE THREAD

**Issue by AbzRaider** [MotorolaMobilityLLC/kernel-mtk#71]
Please release the latest linux kernel source for the device asap.

**Comment by asbraga-motorola** [comment]
Hi @AbzRaider 
Can you inform the exact released version you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

**Comment by sandeepongh** [comment]
S3SV32.45-24-3 seems to be the latest available for MOTO G72

uname -r output:  5.10.110-android12-9-00005-g4fc5e12e2daf-ab8748924

**Comment by AbzRaider** [comment]
@asbraga-motorola when release ?

**Comment by atulnakul121** [comment]
@asbraga-motorola @thenoelboi release when?
Waiting from November.

**Comment by atulnakul121** [comment]
Sir please release it soon.
Atleast please reply.

**Comment by atulnakul121** [comment]
> Please release the latest linux kernel source for the device asap.

Release soon @asbraga-motorola

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3SV32.45-24-3
Thank you all for your patience.
