### ISSUE TITLE
Please release as soon as possible 

### ISSUE THREAD

**Issue by atulnakul121** [MotorolaMobilityLLC/kernel-mtk#73]
Please release kernel source for Moto G72(Vicky).
Build no S3SVS32.45-24-3-2.

**Comment by atulnakul121** [comment]
Chipset mtk G99

**Comment by chenyt9** [comment]
@atulnakul121 ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3SSV32.45-24-3-2
