### ISSUE TITLE
Moto G60s(lisbon)(XT2133-1)kernel sources S3RLS32.114-25-5

### ISSUE THREAD

**Issue by kiev12** [MotorolaMobilityLLC/kernel-mtk#75]
Pls send kernel source moto g60s

**Comment by chenyt9** [comment]
@kiev12 ,
We need more information to ensure the released version meets your needs, so please let me know which version you need. 
Here is an earlier version:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRL31.Q2X-70-44

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3RLS32.114-25-5

**Comment by asbraga-motorola** [comment]
This release has been fixed, label recreated.
see https://github.com/MotorolaMobilityLLC/kernel-mtk/issues/88#issuecomment-1695611155
