### ISSUE TITLE
GPL | Source request for Motorola Moto G31(w) (XT2173-3) S3RWDS32.123-29-2-2

### ISSUE THREAD

**Issue by miklosakos** [MotorolaMobilityLLC/kernel-mtk#76]
I would like to request Kernel, Vendor source tree with the appropriate device tree and blobs for the following device: Motorola Moto G31(w) XT2173-3, running Build number S3RWDS32.123-29-2-2, Android 12, February 1st 2023 security patch from software channel "reteu".

**Comment by electimon** [comment]
@chenyt9

**Comment by electimon** [comment]
@chenyt9 bump

**Comment by electimon** [comment]
@chenyt9 please.

**Comment by miklosakos** [comment]
> @chenyt9 please.

Pinging Chen constantly won't help, let's be real.

**Comment by electimon** [comment]
It won't not help either

**Comment by miklosakos** [comment]
Since this went nowhere for 2 months I contacted Motorola/Lenovo Hungary about this request.
![image](https://github.com/MotorolaMobilityLLC/kernel-mtk/assets/8452012/305ff6da-741b-4098-8851-89d517b48663)

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3RWDS32.123-29-2-2
