### ISSUE TITLE
[Request] Motorola  g73 5G (devonf) android13 Kernel Sources (T1TN33.14-44-2)

### ISSUE THREAD

**Issue by Venkat3620** [MotorolaMobilityLLC/kernel-mtk#77]
Sir @chenyt9 @motorolamobility @asbraga-motorola ,
Please release mtk modules,moto modules,kernel tree for the moto g73 (devonf) T1TN33.14-44-2

**Comment by chenyt9** [comment]
@Venkat3620 ,
pls use this version first：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T1TN33.14-32-4
I have just triggered the open source process of the T1TN33.14-44-2 version
Please be patient, thanks a lot!

**Comment by chenyt9** [comment]
@Venkat3620 
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T1TN33.14-44-2
