### ISSUE TITLE
[Request] Kernel source code for new Motorola Edge 40

### ISSUE THREAD

**Issue by switch-gott** [MotorolaMobilityLLC/kernel-mtk#78]
Hi Team,
please release complete and working kernel source for device motorola edge 40 and android 13.
realy thanks
kind regards

**Comment by asbraga-motorola** [comment]
Can you inform the exact released version you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

**Comment by chenyt9** [comment]
Hi,@switch-gott 
you can refer to these versions first, for the other version, could you inform the exact released version you want? Thanks.
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T2TL33.3-15-4
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T2TL33.3-22-5

**Comment by asbraga-motorola** [comment]
I'm closing this issue because it's open for a long time without a reply.
Please open a new one with the specific BUILD ID if necessary.
