### ISSUE TITLE
 [Request] Moto e6s (fiji_64) Kernel sources - POES29.288-60-6-1-29

### ISSUE THREAD

**Issue by pmagixc** [MotorolaMobilityLLC/kernel-mtk#79]
Hello, could you guys please release kernel source for the e6s 4/64 version, fiji_64?

**Comment by asbraga-motorola** [comment]
Can you inform the exact released version you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

**Comment by pmagixc** [comment]
> Can you inform the exact released version you want? You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

by any chance, is it this? POES29.288-60-6-1-29
or maybe this? PQ2A.190405.003

**Comment by pmagixc** [comment]
when 💀

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-POES29.288-60-6-1-29
