### ISSUE TITLE
GPL | Source request for Motorola Edge 40 (XT2303) (lyriq) T2TL33M.3-22-5

### ISSUE THREAD

**Issue by FuccDucc** [MotorolaMobilityLLC/kernel-mtk#80]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 40 (lyriq) version `T2TL33M.3-22-5`

Model numbers: `XT2303-1`, `XT2303-2`, `XT2303-2-DS`, `XT2303-2-SS`
Codename: `lyriq`

TAG=T2TL33M.3-22-5

** It's mediatek.. i put in the wrong repository first, now i move it from msm to mtk

**Comment by chenyt9** [comment]
@FuccDucc ,
for Motorola edge 40, we only shipped a version:T2TL33.3-15-4
This version of TTL33.51 is no found. Pls, make a double confirm.
For T2TL33.3-15-4, you can refer to:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T2TL33.3-15-4

**Comment by FuccDucc** [comment]
Correction: T2TL33M.3-22-5

> @FuccDucc , for Motorola edge 40, we only shipped a version:T2TL33.3-15-4 This version of TTL33.51 is no found. Pls, make a double confirm

@chenyt9 Correction: T2TL33M.3-22-5 is what i want.
Proof of existance:
```
ro.system.build.fingerprint=motorola/lyriq_g/lyriq:13/T2TL33M.3-22-5/3c37c:user/release-keys
ro.build.version.security_patch=2023-04-01
ro.build.date=Sat Apr 22 08:57:45 CDT 2023
ro.build.date.utc=1682171865
ro.build.type=user
ro.build.user=hudsoncm
ro.build.host=ilclbld185

ro.product.system.brand=motorola
ro.product.system.device=lyriq
ro.product.system.manufacturer=motorola
ro.product.system.model=motorola edge 40
ro.product.system.name=lyriq_g

```

> for Motorola edge 40, we only shipped a version:T2TL33.3-15-4

^^ Not true.. the requested T2TL33M.3-22-5 is newer version, the latest

**Comment by CloudedQuartz** [comment]
For the record, update T2TL33.3-22-9 has also been pushed yet source code has not been released

**Comment by CloudedQuartz** [comment]
LYRIQ_G_T2TL33.3-49-2 update has been pushed also, yet source has not been released

**Comment by chenyt9** [comment]
T2TL33.3-22-5 version is released:

https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T2TL33.3-22-5

**Comment by chenyt9** [comment]
@CloudedQuartz 
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T2TL33.3-22-9

**Comment by chenyt9** [comment]
@CloudedQuartz 
MMI-T2TL33.3-49-2 version is here：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T2TL33.3-49-2
