### ISSUE TITLE
[Request] Kernel sources for Motorola Edge (2022) codename tesla

### ISSUE THREAD

**Issue by mfossen** [MotorolaMobilityLLC/kernel-mtk#81]
Hello! Please release kernel sources for Motorola Edge (2022) codename `tesla`.

Build number: S2STS32.71-118-4-2

Thanks!

**Comment by rangersix7** [comment]
Hey mfossen. Me too...Please release kernel source for Motorola Edge 2022 XT2205 code name Tesla.
I don't think it is Motorola not releasing the source code as much as it is MediaTek. MediaTek just does enough to keep GPL happy. We can hope and ask..

**Comment by chenyt9** [comment]
@all, pls use this verion first:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S2ST32.71-89
The open source process of version S2STS32.71-118-4-2 is already in our workflow.
Please be patient. Thanks.

**Comment by mfossen** [comment]
Thank you @chenyt9!

**Comment by rangersix7** [comment]
Thank you chenyt9

**Comment by chenyt9** [comment]
@rangersix7 ，Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S2STS32.71-118-4-2
