### ISSUE TITLE
Motorola Edge 40 (lyriq) T2TL33M.3-22-5 source

### ISSUE THREAD

**Issue by CloudedQuartz** [MotorolaMobilityLLC/kernel-mtk#85]
Hi, please release kernel tree for Moto Edge 40 (lyriq)

Also, modules have not been released for any version of lyriq, though kernel source for MMI-T2TL33.3-15-4 has been released.

**Comment by FuccDucc** [comment]
Already requested @ #80

**Comment by CloudedQuartz** [comment]
Closing, duplicate of #80
