### ISSUE TITLE
GPL | Source request for Motorola Moto G31(w) (XT2173-3) S3RWDS32.123-29-8-4

### ISSUE THREAD

**Issue by miklosakos** [MotorolaMobilityLLC/kernel-mtk#86]
I would like to request Kernel, Vendor source tree with the appropriate device tree and blobs for the following device: Motorola Moto G31(w) XT2173-3, running Build number S3RWDS32.123-29-8-4, Android 12, June 1st 2023 security patch from software channel "reteu".

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3RWDS32.123-29-8-4
