### ISSUE TITLE
kernel sources, drivers, firmware and vendor blobs of moto e-13 - TLA33.105-226-2

### ISSUE THREAD

**Issue by arunkumar413** [MotorolaMobilityLLC/kernel-mtk#87]
Hi Team,

Could you please release the kernel source, drivers, firmware and vendor blobs of moto e-13 (https://www.motorola.in/smartphones-moto-e13/p?skuId=318)

Thanks,
Arun

**Comment by asbraga-motorola** [comment]
Hi @arunkumar413 
Can you inform the exact released version (Build ID) you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

**Comment by arunkumar413** [comment]
@asbraga-motorola I didn't buy the mobile yet. I plan to buy it once I have the necessary source code and blobs. Does the source code vary from one mobile to another despite being of the same model?

**Comment by asbraga-motorola** [comment]
Yes, we need the Build ID for releasing the exact version.

**Comment by arunkumar413** [comment]
This requirement is for porting capyloon https://capyloon.org/ to moto e-13 . It requires kernel sources and device trees for porting. Do you also release the device tree as well? If not please let me know the process to fetch device tree as well

**Comment by arunkumar413** [comment]
> This requirement is for porting capyloon https://capyloon.org/ to moto e-13 . It requires kernel sources and device trees for porting. Do you also release the device tree as well? If not please let me know the process to fetch device tree as well

@asbraga-motorola Could you please look into this

**Comment by asbraga-motorola** [comment]
You need to inform a build id. We publish the corresponding kernel, device trees and other open source code, all under the same tag for that build id.

**Comment by arunkumar413** [comment]
@asbraga-motorola Here is the build id: TLA33. 105-226-2 

Not sure if there should be a space after 33. Attaching the image for your reference.

![IMG_20230828_231851.jpg](https://github.com/MotorolaMobilityLLC/kernel-mtk/assets/7776779/01f76167-be19-4f8d-b3d8-31e093fb828e)

**Comment by arunkumar413** [comment]
@asbraga-motorola Any update on this?

**Comment by arunkumar413** [comment]
@asbraga-motorola Please let me know if this will take some more time.

**Comment by asbraga-motorola** [comment]
It's in the process to be released, may take some time.

**Comment by arunkumar413** [comment]
@asbraga-motorola Just wanted to check if there is any progress on this request.

**Comment by asbraga-motorola** [comment]
The code has been published in the kernel-sprd repo:
https://github.com/MotorolaMobilityLLC/kernel-sprd/tree/MMI-TLA33.105-226-2
