### ISSUE TITLE
[LISBON][MMI-S3RLS32.114-25-5] released source not matching kernel on phone 

### ISSUE THREAD

**Issue by fuyukihidekii** [MotorolaMobilityLLC/kernel-mtk#88]
Hi there, Apparently an incorrect kernel version was released for this TAG.

https://github.com/MotorolaMobilityLLC/kernel-mtk/commits/MMI-S3RLS32.114-25-5

Device reports 4.14.186+

Source released is 4.19.191

Kindly and cordially could you upload the code corresponding to the S3RLS32.114-25-5 tag or release S3RLS32.114-25-13?

Thanks in advance.

**Comment by asbraga-motorola** [comment]
Fixed: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3RLS32.114-25-5

Please note that I deleted the old tag and created a new one with the same name.

This is the right commit for the tag:
```
git rev-list -n 1 MMI-S3RLS32.114-25-5
2050f6724ac555846f4923dde373e66b9e552d1b
```

If you get a different value, you should delete the local tag and fetch it again:
```
git tag -d MMI-S3RLS32.114-25-5
git fetch origin tag MMI-S3RLS32.114-25-5
```

**Comment by fuyukihidekii** [comment]
Thank you, fix confirmed.
