### ISSUE TITLE
Request : Kernel sources for Motorola edge 40 neo

### ISSUE THREAD

**Issue by the-arxyn** [MotorolaMobilityLLC/kernel-mtk#90]
Hello moto
I am searching for the kernel sources of Motorola edge 40 neo please provide it to us.

**Comment by asbraga-motorola** [comment]
Can you inform the exact released version (Build ID) you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2, T2TZ33.28-16-19.

**Comment by asbraga-motorola** [comment]
If necessary open a new issue informing the Build ID.
