### ISSUE TITLE
[Request] Kernel source code for motorola G54 5G (T3TD33.16-22-5)

### ISSUE THREAD

**Issue by sarthakroy2002** [MotorolaMobilityLLC/kernel-mtk#91]
Please release kernel sources for motorola G54 5G.

**Comment by asbraga-motorola** [comment]
Can you inform the exact released version (Build ID) you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2, T2TZ33.28-16-19.

**Comment by sarthakroy2002** [comment]
> Can you inform the exact released version (Build ID) you want? You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2, T2TZ33.28-16-19.

T3TD33.16-22-5 is the exact released version

**Comment by Sureshgorai25** [comment]
Now the latest released version is T3TD33.16.51-1-1

**Comment by sarthakroy2002** [comment]
@asbraga-motorola any updates on when it will be released!

**Comment by sarthakroy2002** [comment]
@asbraga-motorola release!

**Comment by sarthakroy2002** [comment]
@mbissaromoto @asbraga-motorola ping on this.. bump plz

**Comment by sarthakroy2002** [comment]
@mbissaromoto @asbraga-motorola Please push!

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T3TD33.16-22-5

**Comment by Sureshgorai25** [comment]
Thanks
