### ISSUE TITLE
device tree of moto e-13

### ISSUE THREAD

**Issue by arunkumar413** [MotorolaMobilityLLC/kernel-mtk#92]
Hi Team,

As per my request here (https://github.com/MotorolaMobilityLLC/kernel-mtk/issues/87) @asbraga-motorola  has uploaded the Kernel sources for the moto E-13  here ( https://github.com/MotorolaMobilityLLC/kernel-sprd/tree/MMI-TLA33.105-226-2). However the device tree seems to be missing. Could you please also upload the device tree?

Thanks,
Arun

**Comment by LONGCHEER-01** [comment]
[Arun Kumar](https://github.com/arunkumar413)
Here the branch ：
https://github.com/MotorolaMobilityLLC/kernel-sprd/tree/android-13-release-tla33
