### ISSUE TITLE
[Request] Kernel source and device tree for Moto G73 5g (T1TN33.14-90-9)

### ISSUE THREAD

**Issue by altaf171** [MotorolaMobilityLLC/kernel-mtk#93]

**Comment by santoshjogdand** [comment]
Kernel source and device tree for Moto G73 5g

**Comment by bb33bb** [comment]
the same request
T1TNS33.14-90-9-2

**Comment by bb33bb** [comment]
![image](https://github.com/MotorolaMobilityLLC/kernel-mtk/assets/5463104/5854017d-f21f-454b-b9ec-59e4629de88d)

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T1TN33.14-90-9

**Comment by bb33bb** [comment]
> Version released: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T1TN33.14-90-9

get!
Thank you!!!

**Comment by altaf171** [comment]
Thank you.
