### ISSUE TITLE
[Request] Kernel sources for T2ST33.105-51-5-2 moto edge 2022

### ISSUE THREAD

**Issue by electimon** [MotorolaMobilityLLC/kernel-mtk#94]
Please and thank you!

**Comment by Hasaber8** [comment]
@mbissaromoto Ping on this ^^

**Comment by Hasaber8** [comment]
@chenyt9 too ^^

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T2ST33.105-51-5-2
