### ISSUE TITLE
[Request] Kernel sources for T3TM33.23-37-11  moto edge 40 neo

### ISSUE THREAD

**Issue by pandit246** [MotorolaMobilityLLC/kernel-mtk#95]
Please Provide the Kernal Source Code of Moto Edge 40 Neo
Build No: T3TM33.23-37-11

**Comment by chenyt9** [comment]
Version released：

https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T3TM33.23-37-11

**Comment by Ajayvankar075** [comment]
make rom for motorola edge 40 neo
