### ISSUE TITLE
[Request]: Kernel sources for MMI-S3RQS32.20-42-10-9-6 and MMI-S3RQS32.20-42-10-9-8

### ISSUE THREAD

**Issue by lexi-the-cute** [MotorolaMobilityLLC/kernel-mtk#96]
I currently see MMI-S3RQS32.20-42-10-9-2 in the sources, but not MMI-S3RQS32.20-42-10-9-6 or MMI-S3RQS32.20-42-10-9-8

**Comment by asbraga-motorola** [comment]
Code published:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3RQS32.20-42-10-9-6
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3RQS32.20-42-10-9-8
