### ISSUE TITLE
[Request]: Kernel sources and device tree for Moto G 5G (2022, austin), build T1SAS33.73-40-6

### ISSUE THREAD

**Issue by irixaligned** [MotorolaMobilityLLC/kernel-mtk#97]
Please provide the kernel source and device tree for the requested build, as far as I can tell the last published version is from October of last year
Build number: T1SAS33.73-40-6

**Comment by irixaligned** [comment]
@asbraga-motorola Apologies for the mention, but I do not know how long I will have this device for and as far as I know I am the only one attempting to do any kind of modification to this device, so I would like to know if there was any progress/is it in the process of being released?

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T1SAS33.73-40-6
