### ISSUE TITLE
Source code request for Motorola edge 40 5g T2TLS33.3-62-3-3

### ISSUE THREAD

**Issue by INFINITYP0WER** [MotorolaMobilityLLC/kernel-mtk#98]
Dear

Please provide us source code for Motorola edge 40 5g

Build number: T2TLS33.3-62-3-3
Device: Motorola edge 40 5g

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T2TLS33.3-62-3-3
