### ISSUE TITLE
Kernel sources S3RWS32.138-29-5-8 motorola g41

### ISSUE THREAD

**Issue by Kenshinfl** [MotorolaMobilityLLC/kernel-mtk#99]
Hello, could you provide the source code of the S3RWS32.138-29-5-8 kernel for motorola g41?

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3RWS32.138-29-5-8
